name: BrowserStack Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
  BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Android Tests

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Build
      run: mvn clean compile

    - name: Run Tests
      run: mvn test

    - name: Upload Reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: Allure Reports
        path: "**/allure-results/"
        retention-days: 90
        if-no-files-found: warn